# Generated by Django 4.0.4 on 2022-05-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encrypt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('message', models.TextField(verbose_name='message to hide')),
                ('original_image', models.ImageField(upload_to='', verbose_name='original image')),
                ('reciever_public_key', models.TextField(verbose_name='reciever public key')),
                ('encrypted_image', models.ImageField(blank=True, editable=False, null=True, upload_to='', verbose_name='encrypted image')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decrypt',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('encrypted_image', models.ImageField(upload_to='', verbose_name='encrypted image')),
                ('message', models.TextField(blank=True, editable=False, null=True, verbose_name='message from image')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
