# Generated by Django 4.0.4 on 2023-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageStegano', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decrypt',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='message from image'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='encrypted_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='encrypted image'),
        ),
    ]
