# Generated by Django 4.0.4 on 2023-03-06 18:52

from django.db import migrations, models
import imageStegano.utils


class Migration(migrations.Migration):

    dependencies = [
        ('imageStegano', '0002_alter_decrypt_message_alter_encrypt_encrypted_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decrypt',
            name='encrypted_image',
            field=models.ImageField(upload_to=imageStegano.utils.upload_path, verbose_name='encrypted image'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='encrypted_image',
            field=models.ImageField(blank=True, null=True, upload_to=imageStegano.utils.upload_path, verbose_name='encrypted image'),
        ),
        migrations.AlterField(
            model_name='encrypt',
            name='original_image',
            field=models.ImageField(upload_to=imageStegano.utils.upload_path, verbose_name='original image'),
        ),
    ]
